# Generated by Django 4.1.7 on 2023-04-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0002_book_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='categories',
            field=models.CharField(choices=[('Action', 'ACTION'), ('Mystery', 'MYSTERY'), ('Fantasy', 'FANTASY'), ('Fiction', 'FICTION'), ('Literature', 'LITERATURE'), ('Novel', 'NOVEL')], max_length=50),
        ),
    ]
