# Generated by Django 4.1.7 on 2023-04-19 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0003_alter_book_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='categories',
            new_name='category',
        ),
    ]
