# Generated by Django 4.1.7 on 2023-04-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0007_customer_phno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phno',
            field=models.CharField(max_length=10),
        ),
    ]
