# Generated by Django 4.2.1 on 2023-05-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0009_alter_customer_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=24, unique=True)),
                ('first_name', models.CharField(max_length=16)),
                ('last_name', models.CharField(max_length=16)),
                ('phno', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=24)),
                ('address', models.TextField()),
                ('amount', models.FloatField()),
                ('duration', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Pending', 'PENDING'), ('Shipped', 'SHIPPED'), ('Delivered', 'DELIVERED'), ('Canceled', 'CANCELED')], max_length=50)),
            ],
        ),
    ]
