# Generated by Django 4.2.1 on 2023-05-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0011_alter_order_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'PENDING'), ('Shipped', 'SHIPPED'), ('Delivered', 'DELIVERED'), ('Canceled', 'CANCELED')], default='Pending', max_length=50),
        ),
    ]
