# Generated by Django 4.2.1 on 2023-05-14 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0012_alter_order_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Product',
        ),
    ]
