# Generated by Django 4.2.1 on 2023-05-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0014_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='wishlist',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
