# Generated by Django 4.2.1 on 2023-05-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0016_alter_customer_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='wishlist',
            field=models.CharField(default='{}', max_length=200),
        ),
    ]
